---
# Dependabot automatically keeps our packages up to date
# Docs: https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
- package-ecosystem: bundler
  versioning-strategy: increase # always increase; this ensures we are just using one version of rubocop
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  reviewers:
  - jekyll/plugin-core
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  reviewers:
  - jekyll/plugin-core
