language: ruby
rvm: 2.5.8
cache:
  directories:
  - /home/travis/.rvm/
  - vendor/bundle
before_install:
- gem update --system --no-document
- gem install bundler --no-document
script: script/cibuild $NWO
env:
- NWO="jekyll/jekyll-admin"
- NWO="jekyll/jekyll-archives"
- NWO="jekyll/jekyll-coffeescript"
- NWO="jekyll/jekyll-commonmark"
- NWO="jekyll/jekyll-compose"
- NWO="jekyll/jekyll-feed"
- NWO="jekyll/github-metadata"
- NWO="jekyll/jekyll-import"
- NWO="jekyll/jekyll-mentions"
- NWO="jekyll/jekyll-redirect-from"
- NWO="jekyll/jekyll-sass-converter"
- NWO="jekyll/jekyll-seo-tag"
- NWO="jekyll/jekyll-sitemap"
- NWO="jekyll/jekyll-watch"
- NWO="benbalter/jekyll-avatar"
matrix:
  # These repos are currently locked to rubocop-jekyll-0.10.x or older
  allow_failures:
    - env: NWO="jekyll/jekyll-admin"
    - env: NWO="jekyll/jekyll-import"
    - env: NWO="jekyll/jekyll-redirect-from"
    - env: NWO="jekyll/jekyll-watch"
    - env: NWO="benbalter/jekyll-avatar"
branches:
  only:
  - master
notifications:
  email: false
